# Setup
title:               "Service-Oriented Architecture and Cloud Computing"
description:         'Service-Oriented Architecture and Cloud Computing'
url:                 https://nglelinh.github.io
baseurl:             '/service-oriented-architecture-and-cloud-computing-iuh'
imgurl:              https://nglelinh.github.io/service-oriented-architecture-and-cloud-computing-iuh/img
paginate:            5
permalink:           pretty

# Multi-language support
languages:           ["en", "vi"]
default_lang:        "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

# Language-specific configurations
t:
  en:
    title: "Service-Oriented Architecture and Cloud Computing"
    description: "Service-Oriented Architecture and Cloud Computing"
    home: "Home"
    chapters: "Chapters"
    language: "Language"
    switch_language: "Switch to Vietnamese"
    required: "Required"
    optional: "Optional"
  vi:
    title: "Kiến trúc hướng dịch vụ và Điện toán đám mây"
    description: "Kiến trúc hướng dịch vụ và Điện toán đám mây"
    home: "Trang chủ"
    chapters: "Các chương"
    language: "Ngôn ngữ"
    switch_language: "Chuyển sang tiếng Anh"
    required: "Bắt buộc"
    optional: "Tùy chọn"
# About/contact
author:
  name:              Nguyen Le Linh
  email:             nglelinh@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

plugins_dir: _plugins

# Collections for multilingual content
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Custom vars
version:             0.0.1
markdown: kramdown

# Analytics
google_analytics_id: ""
